from typing import Tuple, Dict, List

SkillItem = Tuple[str, int]
CHAR_SKILLS: Dict[str, List[SkillItem]] = {
    'assassin': [
        ('HeadSh0t', 5),
        ('0ptics', 5),
        ('Killer', 5),
        ('Precisi0n', 5),
        ('0ne Sh0t 0ne Kill', 5),
        ('B0re', 1),
        ('Vel0city', 5),
        ('Kill C0nfirmed', 5),
        ('At 0ne with the Gun', 5),
        ('Critical Ascensi0n', 1),
        ('Fast Hands', 5),
        ('C0unter Strike', 5),
        ('Fearless', 5),
        ('Ambush', 5),
        ('Rising Sh0t', 5),
        ('Death Mark', 1),
        ('Unf0rseen', 5),
        ('Innervate', 5),
        ('Tw0 Fang', 5),
        ('Death Bl0ss0m', 1),
        ('Killing Bl0w', 5),
        ('Ir0n Hand', 5),
        ('Grim', 5),
        ('Be Like Water', 5),
        ('F0ll0wthr0ugh', 5),
        ('Execute', 1),
        ('Backstab', 5),
        ('Resurgence', 5),
        ('Like The Wind', 5),
        ('Many Must Fall', 1),
    ],
    'commando': [
        ('Sentry', 5),
        ('Ready', 5),
        ('Laser Sight', 5),
        ('Willing', 5),
        ('Onslaught', 5),
        ('Scorched Earth', 1),
        ('Able', 5),
        ('Grenadier', 5),
        ('Crisis Management', 5),
        ('Double Up', 1),
        ('Impact', 5),
        ('Expertise', 5),
        ('Overload', 5),
        ('Metal Storm', 5),
        ('Steady', 5),
        ('Longbow Turret', 1),
        ('Battlefront', 5),
        ('Duty Calls', 5),
        ('Do or Die', 1),
        ('Ranger', 5),
        ('Nuke', 1),
        ('Healthy', 5),
        ('Preparation', 5),
        ('Last Ditch Effort', 5),
        ('Pressure', 5),
        ('Forbearance', 5),
        ('Phalanx Shield', 1),
        ('Quick Charge', 5),
        ('Resourceful', 5),
        ('Mag-Lock', 1),
        ('Grit', 5),
        ('Gemini', 1),
    ],
    'gunzerker': [
        ('Locked And Loaded', 5),
        ('Quick Draw', 5),
        ("I'm Your Huckleberry", 5),
        ('All I Need is One', 5),
        ('Divergent Likeness', 5),
        ('Auto-Loader', 1),
        ('Money Shot', 5),
        ('Lay Waste', 5),
        ('Down Not Out', 1),
        ('Keep It Piping Hot', 5),
        ('No Kill Like Overkill', 1),
        ('Inconceivable', 5),
        ('Filled to the Brim', 5),
        ('All in the Reflexes', 5),
        ('Last Longer', 5),
        ("I'm Ready Already", 5),
        ('Steady as She Goes', 1),
        ('5 Shots or 6', 5),
        ('Yippie Ki Yay', 5),
        ('Double Your Fun', 1),
        ('Get Some', 5),
        ('Keep Firing', 1),
        ('Hard to Kill', 5),
        ('Incite', 5),
        ('Asbestos', 5),
        ("I'm the Juggernaut", 5),
        ("Ain't Got Time To Bleed", 5),
        ('Fistful of Hurt', 1),
        ('All Out of Bubblegum', 5),
        ("Bus That Can't Slow Down", 5),
        ('Just Got Real', 5),
        ('Sexual Tyrannosaurus', 5),
        ('Come At Me, Bro', 1),
    ],
    'mechromancer': [
        ('Close Enough', 5),
        ('Cooking Up Trouble', 5),
        ('Fancy Mathematics', 5),
        ('Buck Up', 1),
        ('The Better Half', 5),
        ('Potent as a Pony', 5),
        ('Upshot Robot', 1),
        ('Unstoppable Force', 5),
        ('Explosive Clap', 1),
        ('Made of Sterner Stuff', 5),
        ('20% Cooler', 5),
        ('Sharing is Caring', 1),
        ('More Pep', 5),
        ('Myelin', 5),
        ('Shock Storm', 5),
        ('The Stare', 1),
        ('Strength of Five Gorillas', 5),
        ('Electrical Burn', 5),
        ('Shock and "AAAGGGGHHH!"', 1),
        ('Evil Enchantress', 5),
        ('One Two Boom', 1),
        ("Wires Don't Talk", 5),
        ('Interspersed Outburst', 5),
        ('Make it Sparkle', 1),
        ('Smaller, Lighter, Faster', 4),
        ('Anarchy', 1),
        ('Preshrunk Cyberpunk', 5),
        ('Robot Rampage', 1),
        ('Blood Soaked Shields', 5),
        ('Annoyed Android', 5),
        ('Discord', 1),
        ('Typecast Iconoclast', 5),
        ('Rational Anarchist', 1),
        ('Death From Above', 5),
        ('The Nth Degree', 5),
        ('With Claws', 1),
    ],
    'psycho': [
        ('Blood-Filled Guns', 5),
        ('Blood Twitch', 5),
        ('Taste of Blood', 5),
        ('Bloody Revival', 5),
        ('Blood Overdrive', 5),
        ('Blood Bath', 5),
        ('Buzz Axe Bombardier', 1),
        ('Fuel the Blood', 5),
        ('Blood Trance', 5),
        ('Boiling Blood', 5),
        ('Nervous Blood', 5),
        ('Bloodsplosion', 1),
        ('Empty the Rage', 5),
        ('Pull the Pin', 1),
        ('Feed the Meat', 5),
        ('Embrace the Pain', 5),
        ('Fuel the Rampage', 5),
        ('Thrill of the Kill', 5),
        ('Light the Fuse', 1),
        ('Strip the Flesh', 5),
        ('Redeem the Soul', 1),
        ('Salt the Wound', 5),
        ('Silence the Voices', 5),
        ('Release the Beast', 1),
        ('Burn, Baby, Burn', 5),
        ('Fuel the Fire', 5),
        ('Numbed Nerves', 5),
        ('Pain is Power', 5),
        ('Elemental Elation', 5),
        ('Delusional Damage', 1),
        ('Fire Fiend', 5),
        ('Flame Flare', 5),
        ('Hellfire Halitosis', 1),
        ('Elemental Empathy', 5),
        ('Raving Retribution', 1),
    ],
    'siren': [
        ('Ward', 5),
        ('Accelerate', 5),
        ('Suspension', 5),
        ('Kinetic Reflection', 5),
        ('Fleet', 5),
        ('Converge', 1),
        ('Inertia', 5),
        ('Quicken', 5),
        ('Sub-Sequence', 5),
        ('Thoughtlock', 1),
        ("Mind's Eye", 5),
        ('Sweet Release', 5),
        ('Restoration', 5),
        ('Wreck', 5),
        ('Elated', 5),
        ('Res', 1),
        ('Recompense', 5),
        ('Sustenance', 5),
        ('Life Tap', 5),
        ('Scorn', 1),
        ('Flicker', 5),
        ('Foresight', 5),
        ('Immolate', 5),
        ('Helios', 5),
        ('Chain Reaction', 5),
        ('Cloud Kill', 1),
        ('Backdraft', 5),
        ('Reaper', 5),
        ('Blight Phoenix', 5),
        ('Ruin', 1),
    ],
}
